server:
  port: 8085
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.25.250.111:3306/gec?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 1087
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 172.25.250.111
    port: 6379
    database: 0
    timeout: 1800000
    password: 1087
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲